name: framework
description: none

publish_to: 'none' 

version: 0.1.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  animate_do: ^2.0.0
  flutter_advanced_drawer: ^1.2.4
  http: ^0.13.3
  url_launcher: ^6.0.15
  dio: ^4.0.4
  path: ^1.8.0
  image_picker: ^0.8.4+4
  image: ^3.1.0
  path_provider: ^2.0.8
  hash_generator: ^0.5.2
  splashscreen: ^1.3.5
  smtpman: ^1.0.2
  floating_navbar: ^2.0.2
  floating_bottom_navigation_bar: ^1.5.2
  dependencies: ^0.1.5
  provider: ^6.0.2
  flutter_phoenix: ^1.0.0
  align_positioned: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  #assets:
     #- assets/images/
